name: Publish NPM Package to Google Artifact Registry
description: 'Publishes an npm package to Google Artifact Registry'
inputs:
  credentials-json:
    description: 'gcloud service account credentials json'
    required: true
  project-id:
    description: 'gcloud project id'
    required: true
  region:
    description: 'artifact registry region'
    required: false
    default: 'us-west1'
  repository:
    description: 'artifact registry repository'
    required: false
    default: 'npm'
  scope:
    description: 'scope to use when publishing'
    required: true
runs:
  using: composite
  steps:
    - uses: crazy-max/ghaction-dump-context@v1
    - uses: actions/checkout@v2
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.credentials-json }}
    - uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ inputs.project-id }}
    - name: Configure NPM
      shell: bash
      run: |
        gcloud artifacts print-settings npm --scope=${{ inputs.scope }} >> ./npmrc
        npx google-artifactregistry-auth
        npm publish